--print("[sl1m] setting post-opts")
--vim.notify = require("notify")
--vim.notify("hola sl1m")
--require("tokyonight").setup({
  -- use the night style
--  style = "day",
  -- disable italic for functions
--  styles = {
--    functions = {}
--  },
  -- Change the "hint" color to the "orange" color, and make the "error" color 
  -- bright red
--  on_colors = function(colors)
--    colors.hint = colors.orange
--    colors.error = "#ff0000"
--  end
--})
--vim.cmd.colorscheme = "tokyonight"
