print("@nvim/after/plugin/telecscope.lua | keybinds|telescope")
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, { desc = 'Telescope find in all files' })
vim.keymap.set('n', '<C-p>', builtin.git_files, { desc = 'Telescope in git files only' })
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
